const records = [
  {
    "REALTORS NAME": "Mary Johnson",
    "DATE OF REG": "2025-01-15",
    "REALTOR ID NO": "R-1001",
    "GENDER": "Female",
    "DATE OF BIRTH": "1990-04-22",
    "ADDRESS OF REALTOR": "12 Okafor Street, Lekki",
    "REALTOR PHONE NO": "08031234567",
    "REALTOR EMAIL ADDRESS": "mary.johnson@gmail.com",
    "COUNTRY OF LOCATION": "Nigeria",
    "PLACE OF REG": "Lagos",
    "STATE CODE": "LA",
    "STATIONED CITY/LGA": "Lekki",
    "REG PAYMENT": "Paid",
    "BANK A/C NO": "0123456789",
    "BANK A/C NAME": "Mary Johnson",
    "BANK": "Zenith Bank",
    "REALTOR NEXT OF KIN NAME": "Grace Johnson",
    "NEXT OF KIN ADDRESS": "12 Okafor Street, Lekki",
    "NEXT OF KIN PHONE NO": "08098765432",
    "REFEREE NAME": "Peter Okafor",
    "REFEREE ID NO": "F-201",
    "REFEREE PHONE NO": "08020000001",
    "REFEREE BANK NAME": "Access Bank",
    "REFEREE BANK A/C NO": "0011223344",
    "REFEREE A/C NAME": "Peter Okafor",
    "INCENTIVE PAYMENT (YES/NO)": "YES"
  },
  {
    "REALTORS NAME": "David Bello",
    "DATE OF REG": "2025-02-03",
    "REALTOR ID NO": "R-1002",
    "GENDER": "Male",
    "DATE OF BIRTH": "1988-08-10",
    "ADDRESS OF REALTOR": "9 Victoria Garden City, Lagos",
    "REALTOR PHONE NO": "08032345678",
    "REALTOR EMAIL ADDRESS": "david.bello@gmail.com",
    "COUNTRY OF LOCATION": "Nigeria",
    "PLACE OF REG": "Lagos",
    "STATE CODE": "LA",
    "STATIONED CITY/LGA": "Lekki",
    "REG PAYMENT": "Paid",
    "BANK A/C NO": "1122334455",
    "BANK A/C NAME": "David Bello",
    "BANK": "UBA",
    "REALTOR NEXT OF KIN NAME": "Bello James",
    "NEXT OF KIN ADDRESS": "9 Victoria Garden City, Lagos",
    "NEXT OF KIN PHONE NO": "08055556666",
    "REFEREE NAME": "Peter Okafor",
    "REFEREE ID NO": "F-201",
    "REFEREE PHONE NO": "08020000001",
    "REFEREE BANK NAME": "Access Bank",
    "REFEREE BANK A/C NO": "0011223344",
    "REFEREE A/C NAME": "Peter Okafor",
    "INCENTIVE PAYMENT (YES/NO)": "NO"
  },
  {
    "REALTORS NAME": "Aisha Yusuf",
    "DATE OF REG": "2025-03-10",
    "REALTOR ID NO": "R-1003",
    "GENDER": "Female",
    "DATE OF BIRTH": "1994-11-12",
    "ADDRESS OF REALTOR": "7 Udo Road, Ikoyi",
    "REALTOR PHONE NO": "08029876543",
    "REALTOR EMAIL ADDRESS": "aisha.yusuf@gmail.com",
    "COUNTRY OF LOCATION": "Nigeria",
    "PLACE OF REG": "Abuja",
    "STATE CODE": "FC",
    "STATIONED CITY/LGA": "Gwarinpa",
    "REG PAYMENT": "Paid",
    "BANK A/C NO": "2233445566",
    "BANK A/C NAME": "Aisha Yusuf",
    "BANK": "First Bank",
    "REALTOR NEXT OF KIN NAME": "Hassan Yusuf",
    "NEXT OF KIN ADDRESS": "7 Udo Road, Ikoyi",
    "NEXT OF KIN PHONE NO": "08044445555",
    "REFEREE NAME": "Jane Mba",
    "REFEREE ID NO": "F-202",
    "REFEREE PHONE NO": "08030000002",
    "REFEREE BANK NAME": "GTBank",
    "REFEREE BANK A/C NO": "5566778899",
    "REFEREE A/C NAME": "Jane Mba",
    "INCENTIVE PAYMENT (YES/NO)": "YES"
  },
  {
    "REALTORS NAME": "Efe Okon",
    "DATE OF REG": "2025-04-17",
    "REALTOR ID NO": "R-1004",
    "GENDER": "Male",
    "DATE OF BIRTH": "1991-06-18",
    "ADDRESS OF REALTOR": "15 Nnewi Street, Asaba",
    "REALTOR PHONE NO": "08036667788",
    "REALTOR EMAIL ADDRESS": "efe.okon@gmail.com",
    "COUNTRY OF LOCATION": "Nigeria",
    "PLACE OF REG": "Asaba",
    "STATE CODE": "ND",
    "STATIONED CITY/LGA": "Asaba",
    "REG PAYMENT": "Paid",
    "BANK A/C NO": "3344556677",
    "BANK A/C NAME": "Efe Okon",
    "BANK": "Sterling Bank",
    "REALTOR NEXT OF KIN NAME": "Nneka Okon",
    "NEXT OF KIN ADDRESS": "15 Nnewi Street, Asaba",
    "NEXT OF KIN PHONE NO": "08077778888",
    "REFEREE NAME": "Peter Okafor",
    "REFEREE ID NO": "F-201",
    "REFEREE PHONE NO": "08020000001",
    "REFEREE BANK NAME": "Access Bank",
    "REFEREE BANK A/C NO": "0011223344",
    "REFEREE A/C NAME": "Peter Okafor",
    "INCENTIVE PAYMENT (YES/NO)": "YES"
  }
];

module.exports = { records };
